version: '3.9'
services:
  flask:
    build: .
    expose:
      - 4000
    container_name: flask-backend
  nginx:
    build: ./nginx/
    ports:
      - "443:443"
      - "5000:80"
    depends_on:
      - flask
    